/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TreasuryStorageV1,
  TreasuryStorageV1Interface,
} from "../../../storage/TreasuryStorage.sol/TreasuryStorageV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_newTreasury",
        type: "address",
      },
    ],
    name: "migrateTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "pull",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TreasuryStorageV1__factory {
  static readonly abi = _abi;
  static createInterface(): TreasuryStorageV1Interface {
    return new utils.Interface(_abi) as TreasuryStorageV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TreasuryStorageV1 {
    return new Contract(address, _abi, signerOrProvider) as TreasuryStorageV1;
  }
}
