/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ControllerMockInterface extends utils.Interface {
  functions: {
    "acceptGovernorship()": FunctionFragment;
    "addDepositToken(address)": FunctionFragment;
    "addRewardsDistributor(address)": FunctionFragment;
    "addSyntheticToken(address)": FunctionFragment;
    "addToDebtTokensOfAccount(address)": FunctionFragment;
    "addToDepositTokensOfAccount(address)": FunctionFragment;
    "debtFloorInUsd()": FunctionFragment;
    "debtOf(address)": FunctionFragment;
    "debtPositionOf(address)": FunctionFragment;
    "depositFee()": FunctionFragment;
    "depositOf(address)": FunctionFragment;
    "depositToken()": FunctionFragment;
    "depositTokenOf(address)": FunctionFragment;
    "everythingStopped()": FunctionFragment;
    "getDebtTokensOfAccount(address)": FunctionFragment;
    "getDepositTokens()": FunctionFragment;
    "getDepositTokensOfAccount(address)": FunctionFragment;
    "getRewardsDistributors()": FunctionFragment;
    "getSyntheticTokens()": FunctionFragment;
    "governor()": FunctionFragment;
    "isDepositTokenExists(address)": FunctionFragment;
    "isSyntheticTokenExists(address)": FunctionFragment;
    "issueFee()": FunctionFragment;
    "liquidate(address,address,uint256,address)": FunctionFragment;
    "masterOracle()": FunctionFragment;
    "mockCall(address,bytes)": FunctionFragment;
    "open()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "proposedGovernor()": FunctionFragment;
    "removeDepositToken(address)": FunctionFragment;
    "removeFromDebtTokensOfAccount(address)": FunctionFragment;
    "removeFromDepositTokensOfAccount(address)": FunctionFragment;
    "removeSyntheticToken(address)": FunctionFragment;
    "repayFee()": FunctionFragment;
    "shutdown()": FunctionFragment;
    "swap(address,address,uint256)": FunctionFragment;
    "sweep(address,address,uint256)": FunctionFragment;
    "syntheticToken()": FunctionFragment;
    "transferGovernorship(address)": FunctionFragment;
    "treasury()": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateDebtFloor(uint256)": FunctionFragment;
    "updateDepositFee(uint256)": FunctionFragment;
    "updateIssueFee(uint256)": FunctionFragment;
    "updateLiquidatorLiquidationFee(uint256)": FunctionFragment;
    "updateMasterOracle(address)": FunctionFragment;
    "updateMaxLiquidable(uint256)": FunctionFragment;
    "updateProtocolLiquidationFee(uint256)": FunctionFragment;
    "updateRepayFee(uint256)": FunctionFragment;
    "updateSwapFee(uint256)": FunctionFragment;
    "updateTreasury(address)": FunctionFragment;
    "updateWithdrawFee(uint256)": FunctionFragment;
    "withdrawFee()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptGovernorship"
      | "addDepositToken"
      | "addRewardsDistributor"
      | "addSyntheticToken"
      | "addToDebtTokensOfAccount"
      | "addToDepositTokensOfAccount"
      | "debtFloorInUsd"
      | "debtOf"
      | "debtPositionOf"
      | "depositFee"
      | "depositOf"
      | "depositToken"
      | "depositTokenOf"
      | "everythingStopped"
      | "getDebtTokensOfAccount"
      | "getDepositTokens"
      | "getDepositTokensOfAccount"
      | "getRewardsDistributors"
      | "getSyntheticTokens"
      | "governor"
      | "isDepositTokenExists"
      | "isSyntheticTokenExists"
      | "issueFee"
      | "liquidate"
      | "masterOracle"
      | "mockCall"
      | "open"
      | "pause"
      | "paused"
      | "proposedGovernor"
      | "removeDepositToken"
      | "removeFromDebtTokensOfAccount"
      | "removeFromDepositTokensOfAccount"
      | "removeSyntheticToken"
      | "repayFee"
      | "shutdown"
      | "swap"
      | "sweep"
      | "syntheticToken"
      | "transferGovernorship"
      | "treasury"
      | "unpause"
      | "updateDebtFloor"
      | "updateDepositFee"
      | "updateIssueFee"
      | "updateLiquidatorLiquidationFee"
      | "updateMasterOracle"
      | "updateMaxLiquidable"
      | "updateProtocolLiquidationFee"
      | "updateRepayFee"
      | "updateSwapFee"
      | "updateTreasury"
      | "updateWithdrawFee"
      | "withdrawFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptGovernorship",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDepositToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addRewardsDistributor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSyntheticToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addToDebtTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addToDepositTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "debtFloorInUsd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "debtOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "debtPositionOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokenOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "everythingStopped",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDebtTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsDistributors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSyntheticTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isDepositTokenExists",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isSyntheticTokenExists",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "issueFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "masterOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "open", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposedGovernor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDepositToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromDebtTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromDepositTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSyntheticToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "repayFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "shutdown", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sweep",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "syntheticToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferGovernorship",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateDebtFloor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDepositFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIssueFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidatorLiquidationFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMasterOracle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxLiquidable",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocolLiquidationFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRepayFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSwapFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWithdrawFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGovernorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDepositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRewardsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSyntheticToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToDebtTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToDepositTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debtFloorInUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debtOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "debtPositionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTokenOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "everythingStopped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebtTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsDistributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSyntheticTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDepositTokenExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSyntheticTokenExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issueFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "masterOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mockCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "open", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposedGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDepositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromDebtTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromDepositTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSyntheticToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shutdown", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "syntheticToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferGovernorship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDebtFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDepositFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIssueFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidatorLiquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMasterOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxLiquidable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocolLiquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRepayFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSwapFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWithdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;

  events: {
    "Open(address)": EventFragment;
    "Paused(address)": EventFragment;
    "Shutdown(address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "UpdatedGovernor(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Open"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Shutdown"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedGovernor"): EventFragment;
}

export interface OpenEventObject {
  account: string;
}
export type OpenEvent = TypedEvent<[string], OpenEventObject>;

export type OpenEventFilter = TypedEventFilter<OpenEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface ShutdownEventObject {
  account: string;
}
export type ShutdownEvent = TypedEvent<[string], ShutdownEventObject>;

export type ShutdownEventFilter = TypedEventFilter<ShutdownEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpdatedGovernorEventObject {
  previousGovernor: string;
  proposedGovernor: string;
}
export type UpdatedGovernorEvent = TypedEvent<
  [string, string],
  UpdatedGovernorEventObject
>;

export type UpdatedGovernorEventFilter = TypedEventFilter<UpdatedGovernorEvent>;

export interface ControllerMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ControllerMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptGovernorship(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    addRewardsDistributor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    addSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    addToDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    addToDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<[BigNumber]>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _debtInUsd: BigNumber }>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _isHealthy: boolean;
        _depositInUsd: BigNumber;
        _debtInUsd: BigNumber;
        _issuableLimitInUsd: BigNumber;
        _issuableInUsd: BigNumber;
      }
    >;

    depositFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    depositToken(overrides?: CallOverrides): Promise<[string]>;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    everythingStopped(overrides?: CallOverrides): Promise<[boolean]>;

    getDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getDepositTokens(overrides?: CallOverrides): Promise<[string[]]>;

    getDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRewardsDistributors(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _rewardsDistributors: string[] }>;

    getSyntheticTokens(overrides?: CallOverrides): Promise<[string[]]>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    isDepositTokenExists(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    issueFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    liquidate(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    masterOracle(overrides?: CallOverrides): Promise<[string]>;

    mockCall(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    open(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    proposedGovernor(overrides?: CallOverrides): Promise<[string]>;

    removeDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    removeFromDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    removeFromDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    removeSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    repayFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    shutdown(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swap(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sweep(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    syntheticToken(overrides?: CallOverrides): Promise<[string]>;

    transferGovernorship(
      _proposedGovernor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateLiquidatorLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    updateMasterOracle(
      _newMasterOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMaxLiquidable(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    updateProtocolLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSwapFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateWithdrawFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    withdrawFee(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  acceptGovernorship(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addDepositToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  addRewardsDistributor(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  addSyntheticToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  addToDebtTokensOfAccount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  addToDepositTokensOfAccount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  debtFloorInUsd(overrides?: CallOverrides): Promise<BigNumber>;

  debtOf(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  debtPositionOf(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
      _isHealthy: boolean;
      _depositInUsd: BigNumber;
      _debtInUsd: BigNumber;
      _issuableLimitInUsd: BigNumber;
      _issuableInUsd: BigNumber;
    }
  >;

  depositFee(overrides?: CallOverrides): Promise<BigNumber>;

  depositOf(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  depositToken(overrides?: CallOverrides): Promise<string>;

  depositTokenOf(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  everythingStopped(overrides?: CallOverrides): Promise<boolean>;

  getDebtTokensOfAccount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getDepositTokens(overrides?: CallOverrides): Promise<string[]>;

  getDepositTokensOfAccount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRewardsDistributors(overrides?: CallOverrides): Promise<string[]>;

  getSyntheticTokens(overrides?: CallOverrides): Promise<string[]>;

  governor(overrides?: CallOverrides): Promise<string>;

  isDepositTokenExists(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSyntheticTokenExists(
    _syntheticToken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  issueFee(overrides?: CallOverrides): Promise<BigNumber>;

  liquidate(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  masterOracle(overrides?: CallOverrides): Promise<string>;

  mockCall(
    _to: PromiseOrValue<string>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  open(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  proposedGovernor(overrides?: CallOverrides): Promise<string>;

  removeDepositToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  removeFromDebtTokensOfAccount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  removeFromDepositTokensOfAccount(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  removeSyntheticToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  repayFee(overrides?: CallOverrides): Promise<BigNumber>;

  shutdown(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swap(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sweep(
    _token: PromiseOrValue<string>,
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  syntheticToken(overrides?: CallOverrides): Promise<string>;

  transferGovernorship(
    _proposedGovernor: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  treasury(overrides?: CallOverrides): Promise<string>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDebtFloor(
    _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDepositFee(
    _newDepositFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateIssueFee(
    _newIssueFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateLiquidatorLiquidationFee(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  updateMasterOracle(
    _newMasterOracle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMaxLiquidable(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  updateProtocolLiquidationFee(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  updateRepayFee(
    _newRepayFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSwapFee(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  updateTreasury(
    _treasury: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateWithdrawFee(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  withdrawFee(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    acceptGovernorship(overrides?: CallOverrides): Promise<void>;

    addDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addRewardsDistributor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addToDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addToDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<BigNumber>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _isHealthy: boolean;
        _depositInUsd: BigNumber;
        _debtInUsd: BigNumber;
        _issuableLimitInUsd: BigNumber;
        _issuableInUsd: BigNumber;
      }
    >;

    depositFee(overrides?: CallOverrides): Promise<BigNumber>;

    depositOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    depositToken(overrides?: CallOverrides): Promise<string>;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    everythingStopped(overrides?: CallOverrides): Promise<boolean>;

    getDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getDepositTokens(overrides?: CallOverrides): Promise<string[]>;

    getDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRewardsDistributors(overrides?: CallOverrides): Promise<string[]>;

    getSyntheticTokens(overrides?: CallOverrides): Promise<string[]>;

    governor(overrides?: CallOverrides): Promise<string>;

    isDepositTokenExists(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    issueFee(overrides?: CallOverrides): Promise<BigNumber>;

    liquidate(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    masterOracle(overrides?: CallOverrides): Promise<string>;

    mockCall(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    open(overrides?: CallOverrides): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    proposedGovernor(overrides?: CallOverrides): Promise<string>;

    removeDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeFromDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeFromDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    repayFee(overrides?: CallOverrides): Promise<BigNumber>;

    shutdown(overrides?: CallOverrides): Promise<void>;

    swap(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sweep(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    syntheticToken(overrides?: CallOverrides): Promise<string>;

    transferGovernorship(
      _proposedGovernor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLiquidatorLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMasterOracle(
      _newMasterOracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaxLiquidable(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProtocolLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSwapFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateWithdrawFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFee(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Open(address)"(account?: null): OpenEventFilter;
    Open(account?: null): OpenEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Shutdown(address)"(account?: null): ShutdownEventFilter;
    Shutdown(account?: null): ShutdownEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "UpdatedGovernor(address,address)"(
      previousGovernor?: PromiseOrValue<string> | null,
      proposedGovernor?: PromiseOrValue<string> | null
    ): UpdatedGovernorEventFilter;
    UpdatedGovernor(
      previousGovernor?: PromiseOrValue<string> | null,
      proposedGovernor?: PromiseOrValue<string> | null
    ): UpdatedGovernorEventFilter;
  };

  estimateGas: {
    acceptGovernorship(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addRewardsDistributor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addToDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addToDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<BigNumber>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositFee(overrides?: CallOverrides): Promise<BigNumber>;

    depositOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositToken(overrides?: CallOverrides): Promise<BigNumber>;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    everythingStopped(overrides?: CallOverrides): Promise<BigNumber>;

    getDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDepositTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardsDistributors(overrides?: CallOverrides): Promise<BigNumber>;

    getSyntheticTokens(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    isDepositTokenExists(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    issueFee(overrides?: CallOverrides): Promise<BigNumber>;

    liquidate(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    masterOracle(overrides?: CallOverrides): Promise<BigNumber>;

    mockCall(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    open(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    proposedGovernor(overrides?: CallOverrides): Promise<BigNumber>;

    removeDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeFromDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeFromDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    repayFee(overrides?: CallOverrides): Promise<BigNumber>;

    shutdown(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swap(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sweep(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    syntheticToken(overrides?: CallOverrides): Promise<BigNumber>;

    transferGovernorship(
      _proposedGovernor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateLiquidatorLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateMasterOracle(
      _newMasterOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMaxLiquidable(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateProtocolLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSwapFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateWithdrawFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawFee(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptGovernorship(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addRewardsDistributor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addToDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addToDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    everythingStopped(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDepositTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardsDistributors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSyntheticTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isDepositTokenExists(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    issueFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidate(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    masterOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockCall(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    open(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposedGovernor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeDepositToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeFromDebtTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeFromDepositTokensOfAccount(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeSyntheticToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    repayFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    shutdown(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sweep(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    syntheticToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferGovernorship(
      _proposedGovernor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateLiquidatorLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateMasterOracle(
      _newMasterOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMaxLiquidable(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateProtocolLiquidationFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSwapFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateWithdrawFee(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
