/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from "./ERC20Mock.sol";
export type { erc20MockSol };
export type { ControllerMock } from "./ControllerMock";
export type { DefaultOracleMock } from "./DefaultOracleMock";
export type { MasterOracleMock } from "./MasterOracleMock";
export type { TokenHolderMock } from "./TokenHolderMock";
