/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMasterOracle } from "./IMasterOracle";
export type { IOracle } from "./IOracle";
export type { IPriceProvider } from "./IPriceProvider";
export type { IUniswapV3CrossPoolOracle } from "./IUniswapV3CrossPoolOracle";
