/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ControllerStorageV1Interface extends utils.Interface {
  functions: {
    "addDepositToken(address)": FunctionFragment;
    "addRewardsDistributor(address)": FunctionFragment;
    "addSyntheticToken(address)": FunctionFragment;
    "addToDebtTokensOfAccount(address)": FunctionFragment;
    "addToDepositTokensOfAccount(address)": FunctionFragment;
    "debtFloorInUsd()": FunctionFragment;
    "debtOf(address)": FunctionFragment;
    "debtPositionOf(address)": FunctionFragment;
    "depositFee()": FunctionFragment;
    "depositOf(address)": FunctionFragment;
    "depositTokenOf(address)": FunctionFragment;
    "everythingStopped()": FunctionFragment;
    "getDebtTokensOfAccount(address)": FunctionFragment;
    "getDepositTokens()": FunctionFragment;
    "getDepositTokensOfAccount(address)": FunctionFragment;
    "getRewardsDistributors()": FunctionFragment;
    "getSyntheticTokens()": FunctionFragment;
    "isDepositTokenExists(address)": FunctionFragment;
    "isSyntheticTokenExists(address)": FunctionFragment;
    "issueFee()": FunctionFragment;
    "liquidate(address,address,uint256,address)": FunctionFragment;
    "liquidatorLiquidationFee()": FunctionFragment;
    "masterOracle()": FunctionFragment;
    "maxLiquidable()": FunctionFragment;
    "paused()": FunctionFragment;
    "protocolLiquidationFee()": FunctionFragment;
    "removeDepositToken(address)": FunctionFragment;
    "removeFromDebtTokensOfAccount(address)": FunctionFragment;
    "removeFromDepositTokensOfAccount(address)": FunctionFragment;
    "removeSyntheticToken(address)": FunctionFragment;
    "repayFee()": FunctionFragment;
    "swap(address,address,uint256)": FunctionFragment;
    "swapFee()": FunctionFragment;
    "treasury()": FunctionFragment;
    "updateDebtFloor(uint256)": FunctionFragment;
    "updateDepositFee(uint256)": FunctionFragment;
    "updateIssueFee(uint256)": FunctionFragment;
    "updateLiquidatorLiquidationFee(uint256)": FunctionFragment;
    "updateMasterOracle(address)": FunctionFragment;
    "updateMaxLiquidable(uint256)": FunctionFragment;
    "updateProtocolLiquidationFee(uint256)": FunctionFragment;
    "updateRepayFee(uint256)": FunctionFragment;
    "updateSwapFee(uint256)": FunctionFragment;
    "updateTreasury(address)": FunctionFragment;
    "updateWithdrawFee(uint256)": FunctionFragment;
    "withdrawFee()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addDepositToken"
      | "addRewardsDistributor"
      | "addSyntheticToken"
      | "addToDebtTokensOfAccount"
      | "addToDepositTokensOfAccount"
      | "debtFloorInUsd"
      | "debtOf"
      | "debtPositionOf"
      | "depositFee"
      | "depositOf"
      | "depositTokenOf"
      | "everythingStopped"
      | "getDebtTokensOfAccount"
      | "getDepositTokens"
      | "getDepositTokensOfAccount"
      | "getRewardsDistributors"
      | "getSyntheticTokens"
      | "isDepositTokenExists"
      | "isSyntheticTokenExists"
      | "issueFee"
      | "liquidate"
      | "liquidatorLiquidationFee"
      | "masterOracle"
      | "maxLiquidable"
      | "paused"
      | "protocolLiquidationFee"
      | "removeDepositToken"
      | "removeFromDebtTokensOfAccount"
      | "removeFromDepositTokensOfAccount"
      | "removeSyntheticToken"
      | "repayFee"
      | "swap"
      | "swapFee"
      | "treasury"
      | "updateDebtFloor"
      | "updateDepositFee"
      | "updateIssueFee"
      | "updateLiquidatorLiquidationFee"
      | "updateMasterOracle"
      | "updateMaxLiquidable"
      | "updateProtocolLiquidationFee"
      | "updateRepayFee"
      | "updateSwapFee"
      | "updateTreasury"
      | "updateWithdrawFee"
      | "withdrawFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addDepositToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addRewardsDistributor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSyntheticToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addToDebtTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addToDepositTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "debtFloorInUsd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "debtOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "debtPositionOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokenOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "everythingStopped",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDebtTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardsDistributors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSyntheticTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDepositTokenExists",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isSyntheticTokenExists",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "issueFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatorLiquidationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "masterOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLiquidable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolLiquidationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDepositToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromDebtTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromDepositTokensOfAccount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSyntheticToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "repayFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "swapFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateDebtFloor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDepositFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIssueFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidatorLiquidationFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMasterOracle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxLiquidable",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocolLiquidationFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRepayFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSwapFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWithdrawFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addDepositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRewardsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSyntheticToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToDebtTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToDepositTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debtFloorInUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debtOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "debtPositionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositTokenOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "everythingStopped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebtTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardsDistributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSyntheticTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDepositTokenExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSyntheticTokenExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issueFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidatorLiquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "masterOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLiquidable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolLiquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDepositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromDebtTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromDepositTokensOfAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSyntheticToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDebtFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDepositFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIssueFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidatorLiquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMasterOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxLiquidable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocolLiquidationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRepayFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSwapFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWithdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ControllerStorageV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ControllerStorageV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addRewardsDistributor(
      _distributor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addToDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addToDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<[BigNumber]>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _debtInUsd: BigNumber }>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _isHealthy: boolean;
        _depositInUsd: BigNumber;
        _debtInUsd: BigNumber;
        _issuableLimitInUsd: BigNumber;
        _issuableInUsd: BigNumber;
      }
    >;

    depositFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        _depositInUsd: BigNumber;
        _issuableLimitInUsd: BigNumber;
      }
    >;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    everythingStopped(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getDepositTokens(overrides?: CallOverrides): Promise<[string[]]>;

    getDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRewardsDistributors(overrides?: CallOverrides): Promise<[string[]]>;

    getSyntheticTokens(overrides?: CallOverrides): Promise<[string[]]>;

    isDepositTokenExists(
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    issueFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    liquidate(
      _syntheticToken: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amountToRepay: PromiseOrValue<BigNumberish>,
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    liquidatorLiquidationFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    masterOracle(overrides?: CallOverrides): Promise<[string]>;

    maxLiquidable(overrides?: CallOverrides): Promise<[BigNumber]>;

    paused(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    protocolLiquidationFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeFromDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeFromDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    repayFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    swap(
      _syntheticTokenIn: PromiseOrValue<string>,
      _syntheticTokenOut: PromiseOrValue<string>,
      _amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateLiquidatorLiquidationFee(
      _newLiquidatorLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMasterOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMaxLiquidable(
      _newMaxLiquidable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateProtocolLiquidationFee(
      _newProtocolLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSwapFee(
      _newSwapFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateTreasury(
      _newTreasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateWithdrawFee(
      _newWithdrawFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFee(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addDepositToken(
    _depositToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addRewardsDistributor(
    _distributor: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addSyntheticToken(
    _synthetic: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addToDebtTokensOfAccount(
    _account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addToDepositTokensOfAccount(
    _account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  debtFloorInUsd(overrides?: CallOverrides): Promise<BigNumber>;

  debtOf(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  debtPositionOf(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
      _isHealthy: boolean;
      _depositInUsd: BigNumber;
      _debtInUsd: BigNumber;
      _issuableLimitInUsd: BigNumber;
      _issuableInUsd: BigNumber;
    }
  >;

  depositFee(overrides?: CallOverrides): Promise<BigNumber>;

  depositOf(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      _depositInUsd: BigNumber;
      _issuableLimitInUsd: BigNumber;
    }
  >;

  depositTokenOf(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  everythingStopped(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getDebtTokensOfAccount(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getDepositTokens(overrides?: CallOverrides): Promise<string[]>;

  getDepositTokensOfAccount(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRewardsDistributors(overrides?: CallOverrides): Promise<string[]>;

  getSyntheticTokens(overrides?: CallOverrides): Promise<string[]>;

  isDepositTokenExists(
    _depositToken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSyntheticTokenExists(
    _syntheticToken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  issueFee(overrides?: CallOverrides): Promise<BigNumber>;

  liquidate(
    _syntheticToken: PromiseOrValue<string>,
    _account: PromiseOrValue<string>,
    _amountToRepay: PromiseOrValue<BigNumberish>,
    _depositToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  liquidatorLiquidationFee(overrides?: CallOverrides): Promise<BigNumber>;

  masterOracle(overrides?: CallOverrides): Promise<string>;

  maxLiquidable(overrides?: CallOverrides): Promise<BigNumber>;

  paused(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  protocolLiquidationFee(overrides?: CallOverrides): Promise<BigNumber>;

  removeDepositToken(
    _depositToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeFromDebtTokensOfAccount(
    _account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeFromDepositTokensOfAccount(
    _account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeSyntheticToken(
    _synthetic: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  repayFee(overrides?: CallOverrides): Promise<BigNumber>;

  swap(
    _syntheticTokenIn: PromiseOrValue<string>,
    _syntheticTokenOut: PromiseOrValue<string>,
    _amountIn: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapFee(overrides?: CallOverrides): Promise<BigNumber>;

  treasury(overrides?: CallOverrides): Promise<string>;

  updateDebtFloor(
    _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDepositFee(
    _newDepositFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateIssueFee(
    _newIssueFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateLiquidatorLiquidationFee(
    _newLiquidatorLiquidationFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMasterOracle(
    _newOracle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMaxLiquidable(
    _newMaxLiquidable: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateProtocolLiquidationFee(
    _newProtocolLiquidationFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRepayFee(
    _newRepayFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSwapFee(
    _newSwapFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateTreasury(
    _newTreasury: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateWithdrawFee(
    _newWithdrawFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFee(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addRewardsDistributor(
      _distributor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addToDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addToDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<BigNumber>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _isHealthy: boolean;
        _depositInUsd: BigNumber;
        _debtInUsd: BigNumber;
        _issuableLimitInUsd: BigNumber;
        _issuableInUsd: BigNumber;
      }
    >;

    depositFee(overrides?: CallOverrides): Promise<BigNumber>;

    depositOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        _depositInUsd: BigNumber;
        _issuableLimitInUsd: BigNumber;
      }
    >;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    everythingStopped(overrides?: CallOverrides): Promise<boolean>;

    getDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getDepositTokens(overrides?: CallOverrides): Promise<string[]>;

    getDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRewardsDistributors(overrides?: CallOverrides): Promise<string[]>;

    getSyntheticTokens(overrides?: CallOverrides): Promise<string[]>;

    isDepositTokenExists(
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    issueFee(overrides?: CallOverrides): Promise<BigNumber>;

    liquidate(
      _syntheticToken: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amountToRepay: PromiseOrValue<BigNumberish>,
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidatorLiquidationFee(overrides?: CallOverrides): Promise<BigNumber>;

    masterOracle(overrides?: CallOverrides): Promise<string>;

    maxLiquidable(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    protocolLiquidationFee(overrides?: CallOverrides): Promise<BigNumber>;

    removeDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeFromDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeFromDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    repayFee(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      _syntheticTokenIn: PromiseOrValue<string>,
      _syntheticTokenOut: PromiseOrValue<string>,
      _amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapFee(overrides?: CallOverrides): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<string>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLiquidatorLiquidationFee(
      _newLiquidatorLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMasterOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaxLiquidable(
      _newMaxLiquidable: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProtocolLiquidationFee(
      _newProtocolLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSwapFee(
      _newSwapFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTreasury(
      _newTreasury: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateWithdrawFee(
      _newWithdrawFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFee(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addRewardsDistributor(
      _distributor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addToDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addToDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<BigNumber>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositFee(overrides?: CallOverrides): Promise<BigNumber>;

    depositOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    everythingStopped(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDepositTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardsDistributors(overrides?: CallOverrides): Promise<BigNumber>;

    getSyntheticTokens(overrides?: CallOverrides): Promise<BigNumber>;

    isDepositTokenExists(
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    issueFee(overrides?: CallOverrides): Promise<BigNumber>;

    liquidate(
      _syntheticToken: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amountToRepay: PromiseOrValue<BigNumberish>,
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    liquidatorLiquidationFee(overrides?: CallOverrides): Promise<BigNumber>;

    masterOracle(overrides?: CallOverrides): Promise<BigNumber>;

    maxLiquidable(overrides?: CallOverrides): Promise<BigNumber>;

    paused(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    protocolLiquidationFee(overrides?: CallOverrides): Promise<BigNumber>;

    removeDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeFromDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeFromDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    repayFee(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      _syntheticTokenIn: PromiseOrValue<string>,
      _syntheticTokenOut: PromiseOrValue<string>,
      _amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapFee(overrides?: CallOverrides): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateLiquidatorLiquidationFee(
      _newLiquidatorLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMasterOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMaxLiquidable(
      _newMaxLiquidable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateProtocolLiquidationFee(
      _newProtocolLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSwapFee(
      _newSwapFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateTreasury(
      _newTreasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateWithdrawFee(
      _newWithdrawFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFee(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addRewardsDistributor(
      _distributor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addToDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addToDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    debtFloorInUsd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    debtOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    debtPositionOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositOf(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositTokenOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    everythingStopped(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDepositTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardsDistributors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSyntheticTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isDepositTokenExists(
      _depositToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSyntheticTokenExists(
      _syntheticToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    issueFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidate(
      _syntheticToken: PromiseOrValue<string>,
      _account: PromiseOrValue<string>,
      _amountToRepay: PromiseOrValue<BigNumberish>,
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    liquidatorLiquidationFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    masterOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxLiquidable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    protocolLiquidationFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeDepositToken(
      _depositToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeFromDebtTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeFromDepositTokensOfAccount(
      _account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeSyntheticToken(
      _synthetic: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    repayFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swap(
      _syntheticTokenIn: PromiseOrValue<string>,
      _syntheticTokenOut: PromiseOrValue<string>,
      _amountIn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateDebtFloor(
      _newDebtFloorInUsd: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDepositFee(
      _newDepositFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateIssueFee(
      _newIssueFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateLiquidatorLiquidationFee(
      _newLiquidatorLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMasterOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMaxLiquidable(
      _newMaxLiquidable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateProtocolLiquidationFee(
      _newProtocolLiquidationFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRepayFee(
      _newRepayFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSwapFee(
      _newSwapFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateTreasury(
      _newTreasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateWithdrawFee(
      _newWithdrawFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
