name: foundry tests
on:
  pull_request:
    paths:
      - "test/foundry/**/*.sol"
      - "contracts/**/*.sol"
      - package*.json
      - ".github/env.properties"
      - ".github/workflows/foundry.yml"

jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm i

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        env:
          MAINNET_NODE_URL: ${{ secrets.MAINNET_NODE_URL }}
          OPTIMISM_NODE_URL: ${{ secrets.OPTIMISM_NODE_URL }}
          BASE_NODE_URL: ${{ secrets.BASE_NODE_URL }}
          PLASMA_NODE_URL: ${{ secrets.PLASMA_NODE_URL }}
