/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  OracleHelpers,
  OracleHelpersInterface,
} from "../../lib/OracleHelpers";

const _abi = [
  {
    inputs: [],
    name: "USD_DECIMALS",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608b610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80632f6ee695146038575b600080fd5b603f601281565b60405160ff909116815260200160405180910390f3fea2646970667358221220c204fa9b1174b574bc137b490250a897aec7cd7ad01c3ee7f850fb898e23682764736f6c63430008090033";

type OracleHelpersConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OracleHelpersConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OracleHelpers__factory extends ContractFactory {
  constructor(...args: OracleHelpersConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<OracleHelpers> {
    return super.deploy(overrides || {}) as Promise<OracleHelpers>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): OracleHelpers {
    return super.attach(address) as OracleHelpers;
  }
  override connect(signer: Signer): OracleHelpers__factory {
    return super.connect(signer) as OracleHelpers__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OracleHelpersInterface {
    return new utils.Interface(_abi) as OracleHelpersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OracleHelpers {
    return new Contract(address, _abi, signerOrProvider) as OracleHelpers;
  }
}
